net: rockchip_wlan: rtl8822cs: Replace complete_and_exit with kthread_complete_and_exit
In commit (cead185: exit: Rename complete_and_exit to kthread_complete_and_exit)
All instances of complete_and_exit were replaced with kthread_complete_and_exit

This fixes following error during compilation:
../drivers/net/wireless/rockchip_wlan/rtl8822cs/os_dep/osdep_service.c:1508:2: error: call to undeclared function 'complete_and_exit'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
 1508 |         complete_and_exit(comp, 0);
      |         ^

Change-Id: I998e7ddde739665d9a16579b7568567d15e74bc0
Signed-off-by: UtsavBalar1231 <utsavbalar1231@gmail.com>